package Interface;

import Domain.Maze;
import javax.swing.JOptionPane;

public class Visual extends javax.swing.JFrame implements Runnable {

    //declaracion de variables
    public int min = 0, seg = 0;
    int[][] matrixGeneral;
    Thread threadChronometer;

    //instancias
    Maze maze = new Maze(matrixGeneral);

    public Visual() {
        initComponents();

        this.setLocationRelativeTo(null);

        threadChronometer = new Thread(this);

        lienzo2.setVisible(false);
        
        btnStart.setEnabled(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo = new javax.swing.ButtonGroup();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        lbCronometro = new javax.swing.JLabel();
        lb_time = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();
        lienzo2 = new Interface.Canvas();
        barra = new javax.swing.JProgressBar();
        labelLoad = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Jmi_Hard = new javax.swing.JMenuItem();
        Jmi_Intermedium = new javax.swing.JMenuItem();
        Jmi_Easy = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("JFreame"); // NOI18N

        lbCronometro.setBackground(new java.awt.Color(204, 0, 0));
        lbCronometro.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbCronometro.setText("Cronometro");

        lb_time.setBackground(new java.awt.Color(255, 0, 0));
        lb_time.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        btnStart.setBackground(new java.awt.Color(255, 255, 255));
        btnStart.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnStart.setForeground(new java.awt.Color(255, 255, 255));
        btnStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iniciar.png"))); // NOI18N
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lienzo2Layout = new javax.swing.GroupLayout(lienzo2);
        lienzo2.setLayout(lienzo2Layout);
        lienzo2Layout.setHorizontalGroup(
            lienzo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 839, Short.MAX_VALUE)
        );
        lienzo2Layout.setVerticalGroup(
            lienzo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1040, Short.MAX_VALUE)
        );

        labelLoad.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        labelLoad.setText("Load Energy...");

        jMenu1.setText("Difficulty");

        Jmi_Hard.setText("Hard");
        Jmi_Hard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jmi_HardActionPerformed(evt);
            }
        });
        jMenu1.add(Jmi_Hard);

        Jmi_Intermedium.setText("Intermedium");
        Jmi_Intermedium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jmi_IntermediumActionPerformed(evt);
            }
        });
        jMenu1.add(Jmi_Intermedium);

        Jmi_Easy.setText("Easy");
        Jmi_Easy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jmi_EasyActionPerformed(evt);
            }
        });
        jMenu1.add(Jmi_Easy);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("System");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCronometro, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_time, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(labelLoad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(barra, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(182, 182, 182)
                .addComponent(lienzo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(748, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(lbCronometro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lb_time, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(barra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(labelLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(lienzo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 305, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        try {
            lienzo2.threadFast.start();
            lienzo2.maze.setF(2);
            threadChronometer.start();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ocurrio un error=" + e.getMessage());
        }
    }//GEN-LAST:event_btnStartActionPerformed

    private void Jmi_HardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jmi_HardActionPerformed
        lienzo2.threadFast.stop();
        lienzo2.setVisible(true);
        
        lienzo2.dificult();

        btnStart.setEnabled(true);
        threadChronometer = new Thread(this);
        min = 0;
        seg = 0;
        lb_time.setText(min + " min: " + seg + " seg: ");
    }//GEN-LAST:event_Jmi_HardActionPerformed

    private void Jmi_IntermediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jmi_IntermediumActionPerformed
        lienzo2.threadFast.stop();
        lienzo2.setVisible(true);

        lienzo2.medium();
        btnStart.setEnabled(true);
        threadChronometer = new Thread(this);
        min = 0;
        seg = 0;
        lb_time.setText(min + " min: " + seg + " seg: ");
    }//GEN-LAST:event_Jmi_IntermediumActionPerformed

    private void Jmi_EasyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jmi_EasyActionPerformed
        lienzo2.threadFast.stop();
        lienzo2.setVisible(true);

        lienzo2.facil();
        btnStart.setEnabled(true);
        threadChronometer = new Thread(this);
        min = 0;
        seg = 0;
        lb_time.setText(min + " min: " + seg + " seg: ");
    }//GEN-LAST:event_Jmi_EasyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Visual().setVisible(true);

            }
        });
    }

    @Override
    public void run() {

        while (true) {
            try {
                Thread.sleep(999);
                seg++;
                if (seg >= 59) {
                    min++;
                    seg = 0;
                }
                lb_time.setText(min + " min: " + seg + " seg ");
                if (lienzo2.maze.getEnd() == 1) {
                    threadChronometer.stop();
                }
            } catch (Exception e) {
            }
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Jmi_Easy;
    private javax.swing.JMenuItem Jmi_Hard;
    private javax.swing.JMenuItem Jmi_Intermedium;
    public static javax.swing.JProgressBar barra;
    private javax.swing.JButton btnStart;
    private javax.swing.ButtonGroup grupo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    public static javax.swing.JLabel labelLoad;
    private javax.swing.JLabel lbCronometro;
    private javax.swing.JLabel lb_time;
    private Interface.Canvas lienzo2;
    // End of variables declaration//GEN-END:variables

}
